apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: existing-canid-go 
  janus-idp.io/tekton: existing-canid-go
  backstage.io/kubernetes-id: existing-canid-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: existing-canid-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  